### ISSUE TITLE
Error in `ast.unparse` on nightly CPython

### ISSUE THREAD

**Issue by Zac-HD** [Zac-HD/stdlib-property-tests#14]
Via #13, we found https://travis-ci.com/github/Zac-HD/stdlib-property-tests/jobs/335728827#L232-L259

```python-traceback
ERROR: test_ast_unparse (test_source_code.TestAST)
Unparsing always produces code which parses back to the same ast.
----------------------------------------------------------------------
  File "<string>", line 1
SyntaxError: unexpected character after line continuation character
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/travis/build/Zac-HD/stdlib-property-tests/tests/test_source_code.py", line 20, in test_ast_unparse
    @given(source_code=hypothesmith.from_grammar())
  File "/home/travis/build/Zac-HD/stdlib-property-tests/.tox/test/lib/python3.9/site-packages/hypothesis/core.py", line 1102, in wrapped_test
    raise the_error_hypothesis_found
  File "/home/travis/build/Zac-HD/stdlib-property-tests/.tox/test/lib/python3.9/site-packages/hypothesmith/syntactic.py", line 86, in draw_symbol
    super().draw_symbol(data, symbol, draw_state)
  File "/home/travis/build/Zac-HD/stdlib-property-tests/.tox/test/lib/python3.9/site-packages/hypothesis/extra/lark.py", line 175, in draw_symbol
    self.draw_symbol(data, e, draw_state)
  File "/home/travis/build/Zac-HD/stdlib-property-tests/.tox/test/lib/python3.9/site-packages/hypothesmith/syntactic.py", line 86, in draw_symbol
    super().draw_symbol(data, symbol, draw_state)
  File "/home/travis/build/Zac-HD/stdlib-property-tests/.tox/test/lib/python3.9/site-packages/hypothesis/extra/lark.py", line 175, in draw_symbol
    self.draw_symbol(data, e, draw_state)
  File "/home/travis/build/Zac-HD/stdlib-property-tests/.tox/test/lib/python3.9/site-packages/hypothesmith/syntactic.py", line 86, in draw_symbol
    super().draw_symbol(data, symbol, draw_state)
  File "/home/travis/build/Zac-HD/stdlib-property-tests/.tox/test/lib/python3.9/site-packages/hypothesis/extra/lark.py", line 175, in draw_symbol
    self.draw_symbol(data, e, draw_state)
  File "/home/travis/build/Zac-HD/stdlib-property-tests/.tox/test/lib/python3.9/site-packages/hypothesmith/syntactic.py", line 89, in draw_symbol
    compile(
SystemError: <built-in function normalize> returned a result with an error set
```

Maybe @pganssle has some idea what's happening here?

**Comment by pganssle** [comment]
@Zac-HD Looks to me like an uncaught error in the C code in CPython, but because the error appears to be in `hypothesmith`, I can't tell what the reproducing case is. I assume it's an error in CPython, possibly related to the new parser. Do you know how to get a more minimal reproducing case? I'm assuming there's a specific input to `compile` that would trigger this.

**Comment by Zac-HD** [comment]
...I think the easiest way to get some output might be to add a special print-this-on-error case to Hypothesmith, I don't have a CPython nightly handy but releasing a new library version is faster anyway :joy:

**Comment by Zac-HD** [comment]
```python
nonlocal𖫬𣩑盙Ѵ𘧮	 	 ;from. 		 import퇉as\		
辚𦱁𘟂痪 ,;global𬪻𓁤㘍𛊤𦡧𦜕𦑚𤆶,   𠶰ꩀ𭋿
		 	
```

is *I think* a reproducing case, if it printed properly and survived from [travis](https://travis-ci.org/github/Zac-HD/stdlib-property-tests/jobs/688073714#L209-L214).

If not, the latest version of Hypothesmith should now raise a more useful error, and if that fails too I'll need to finish rebuilding my desktop, get a proper dev environment set up, and hack on this properly.

**Comment by pganssle** [comment]
I sent this to @pablogsal, he found the issue and posted a release blocker bug: https://bugs.python.org/issue40661

**Comment by Zac-HD** [comment]
Also got [this error](https://travis-ci.org/github/Zac-HD/stdlib-property-tests/jobs/688179390#L310), `unexpected error while attempting to compile 'import𤂴洍𗩺ꐥ𫅦隐𫢯.𣲕䧮럛𐪏𣕹𮡝.㙏𝗫𛅿𡩸𮘿𫶦\\\x0c\x0c\x0c\x0c \x0c \x0c\t\x0c\t \x0c\r\n\r\n' in mode=single`

**Comment by Zac-HD** [comment]
Pretty sure this has been fixed upstream now :slightly_smiling_face:
